apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: testpod
    image: alpine:latest
    command: ["ping", "8.8.8.8"]
    resources:
      requests: 
        memory: 1Mi
        cpu: 1m
      limits:
        memory: 10Mi
        cpu: 25m